CREATE TABLE F16_14_CUSTOMER
(
  CUST_ID NUMBER(5) NOT NULL ,
  CUST_NAME VARCHAR2(20),
  DATE_OF_BIRTH DATE,
  GENDER VARCHAR2(10),
  CUST_EMAIL VARCHAR2(20),
  CITY VARCHAR2(20),
  STREET VARCHAR2(20),
  STATE VARCHAR2(20),
  ZIPCODE VARCHAR2(20),
  PRIMARY KEY (CUST_ID)
);


CREATE SEQUENCE SEQ_CUST
MINVALUE 1
MAXVALUE 9999
START WITH 1
INCREMENT BY 1
CACHE 10;

CREATE OR REPLACE TRIGGER TRIG_CUST_ID
BEFORE INSERT ON F16_14_CUSTOMER
FOR EACH ROW
BEGIN
  SELECT SEQ_CUST.NEXTVAL
  INTO :NEW.CUST_ID
  FROM DUAL;
END;


CREATE TABLE F16_14_CUST_PHONE
(
  CUST_ID NUMBER(5) NOT NULL,
  PHONE_NO NUMBER(10),
  PRIMARY KEY (CUST_ID),
  FOREIGN KEY (CUST_ID) REFERENCES F16_14_CUSTOMER(CUST_ID)
);

CREATE TABLE F16_14_STORE
(
  STORE_ID NUMBER(5) NOT NULL,
  MANAGER_ID NUMBER(5),
  CITY VARCHAR2(20),
  STATE VARCHAR2(20),
  ZIPCODE VARCHAR2(20),
  PRIMARY KEY (STORE_ID)
);


CREATE SEQUENCE SEQ_STORE
MINVALUE 1
MAXVALUE 9999
START WITH 1
INCREMENT BY 1
CACHE 10;

CREATE OR REPLACE TRIGGER TRIG_STORE_ID
BEFORE INSERT ON F16_14_STORE
FOR EACH ROW
BEGIN
  SELECT SEQ_STORE.NEXTVAL
  INTO :NEW.STORE_ID
  FROM DUAL;
END;

CREATE TABLE F16_14_SECTION
(
  STORE_ID NUMBER(5) NOT NULL,
  SECTION_NAME VARCHAR2(20) NOT NULL,
  DATE_FROM DATE,
  DATE_TO DATE,
  PRIMARY KEY (STORE_ID,SECTION_NAME),
  FOREIGN KEY (STORE_ID) REFERENCES F16_14_STORE(STORE_ID)
);


CREATE TABLE F16_14_SUPPLIER
(
  SUPPLIER_ID NUMBER(5) NOT NULL,
  SUPPLIER_NAME VARCHAR2(20),
  PHONE_NO NUMBER(10),
  PERSON_OF_CONTACT VARCHAR2(20),
  ADDRESS VARCHAR2(40),
  PRIMARY KEY (SUPPLIER_ID)
);


CREATE SEQUENCE SEQ_SUPPLIER
MINVALUE 1
MAXVALUE 9999
START WITH 1
INCREMENT BY 1
CACHE 10;

CREATE OR REPLACE TRIGGER TRIG_SUPPLIER_ID
BEFORE INSERT ON F16_14_SUPPLIER
FOR EACH ROW
BEGIN
  SELECT SEQ_SUPPLIER.NEXTVAL
  INTO :NEW.SUPPLIER_ID
  FROM DUAL;
END;


CREATE TABLE F16_14_PRODUCT
(
  PRODUCT_ID NUMBER(5) NOT NULL,
  PRODUCT_NAME VARCHAR2(20),
  SELLING_PRICE NUMBER(5),
  SECTION_NAME VARCHAR2(20),
  PRIMARY KEY (PRODUCT_ID)
);

CREATE SEQUENCE SEQ_PRODUCT
MINVALUE 1
MAXVALUE 9999
START WITH 1
INCREMENT BY 1
CACHE 10;

CREATE OR REPLACE TRIGGER TRIG_PRODUCT_ID
BEFORE INSERT ON F16_14_PRODUCT
FOR EACH ROW
BEGIN
  SELECT SEQ_PRODUCT.NEXTVAL
  INTO :NEW.PRODUCT_ID
  FROM DUAL;
END;


CREATE TABLE F16_14_DISCOUNT
(
  PRODUCT_ID NUMBER(5) NOT NULL,
  DISCOUNT_VALUE NUMBER(5),
  DATE_FROM DATE,
  DATE_TO DATE,
  FOREIGN KEY (PRODUCT_ID) REFERENCES F16_14_PRODUCT(PRODUCT_ID)
);


CREATE TABLE F16_14_EMPLOYEE
(
  EMPLOYEE_ID NUMBER(5) NOT NULL,
  EMPLOYEE_NAME VARCHAR2(20),
  SALARY NUMBER(4),
  ADDRESS VARCHAR2(40),
  STORE_ID NUMBER(5),
  DATE_FROM DATE,
  DATE_TO DATE,
  PRIMARY KEY (EMPLOYEE_ID),
  FOREIGN KEY (STORE_ID) REFERENCES F16_14_STORE(STORE_ID)
);

---Continue from here---

CREATE SEQUENCE SEQ_EMPLOYEE
MINVALUE 1
MAXVALUE 9999
START WITH 1
INCREMENT BY 1
CACHE 10;

CREATE OR REPLACE TRIGGER TRIG_EMPLOYEE_ID
BEFORE INSERT ON F16_14_EMPLOYEE
FOR EACH ROW
BEGIN
  SELECT SEQ_EMPLOYEE.NEXTVAL
  INTO :NEW.EMPLOYEE_ID
  FROM DUAL;
END;


CREATE TABLE F16_14_SALESPERSON
(
  EMPLOYEE_ID NUMBER(5),
  SECTION_NAME VARCHAR2(20),
  PRIMARY KEY (EMPLOYEE_ID),
  FOREIGN KEY (EMPLOYEE_ID) REFERENCES F16_14_EMPLOYEE(EMPLOYEE_ID)
);


CREATE TABLE F16_14_TECHNICIAN
(
  EMPLOYEE_ID NUMBER(5),
  EMPLOYEE_TYPE VARCHAR2(15),
  PRIMARY KEY (EMPLOYEE_ID),
  FOREIGN KEY (EMPLOYEE_ID) REFERENCES F16_14_EMPLOYEE(EMPLOYEE_ID)
);


CREATE TABLE F16_14_BUYS
(
  BUYS_ID NUMBER(5) NOT NULL,
  CUST_ID NUMBER(5),
  STORE_ID NUMBER(5),
  PRODUCT_ID NUMBER(5),
  PRIMARY KEY (BUYS_ID,PRODUCT_ID),
  FOREIGN KEY (CUST_ID) REFERENCES F16_14_CUSTOMER(CUST_ID),
  FOREIGN KEY (STORE_ID) REFERENCES F16_14_STORE(STORE_ID),
  FOREIGN KEY (PRODUCT_ID) REFERENCES F16_14_PRODUCT(PRODUCT_ID)
);


CREATE TABLE F16_14_PURCHASE
(
  BUYS_ID NUMBER(5) NOT NULL,
  PRODUCT_ID NUMBER(5),
  QUANTITY NUMBER(5),
  DATE_OF_PURCHASE DATE,
  PRIMARY KEY (BUYS_ID,PRODUCT_ID),
  FOREIGN KEY (BUYS_ID,PRODUCT_ID) REFERENCES F16_14_BUYS(BUYS_ID,PRODUCT_ID)
);


CREATE TABLE F16_14_PAYMENT
(
  BUYS_ID NUMBER(5) NOT NULL,
  PRODUCT_ID NUMBER(5),
  MODE_OF_PAYMENT VARCHAR2(10),
  BANK_CARD VARCHAR2(20),
  PRIMARY KEY (BUYS_ID,PRODUCT_ID),
  FOREIGN KEY (BUYS_ID,PRODUCT_ID) REFERENCES F16_14_BUYS(BUYS_ID,PRODUCT_ID),
  FOREIGN KEY (PRODUCT_ID) REFERENCES F16_14_PRODUCT(PRODUCT_ID)
);


CREATE TABLE F16_14_SUPPLIES
(
  SUPPLY_ID NUMBER(5) NOT NULL,
  PRODUCT_ID NUMBER(5),
  STORE_ID NUMBER(5),
  SUPPLIER_ID NUMBER(5),
  QUANTITY NUMBER(5),
  DATE_OF_SALE DATE,
  SELLING_PRICE NUMBER(5),
  PRIMARY KEY (SUPPLY_ID),
  FOREIGN KEY (PRODUCT_ID) REFERENCES F16_14_PRODUCT(PRODUCT_ID),
  FOREIGN KEY (STORE_ID) REFERENCES F16_14_STORE(STORE_ID),
  FOREIGN KEY (SUPPLIER_ID) REFERENCES F16_14_SUPPLIER(SUPPLIER_ID)
);

CREATE SEQUENCE SEQ_SUPPLIES
MINVALUE 1
MAXVALUE 9999
START WITH 1
INCREMENT BY 1
CACHE 10;

CREATE OR REPLACE TRIGGER TRIG_SUPPLIES_ID
BEFORE INSERT ON F16_14_SUPPLIES
FOR EACH ROW
BEGIN
  SELECT SEQ_SUPPLIES.NEXTVAL
  INTO :NEW.SUPPLY_ID
  FROM DUAL;
END;
